# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: arnobirchler/gitlab-ci:7.2

stages:
  - build
  - test
  - deploy
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - vendor/

composer:
  stage: build
  script:
    - composer install
    - composer dump-autoload
# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres

acceptance-test:
  stage: test
  before_script:
    - cp .env.testing .env
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan config:cache
    - nohup php artisan serv &
  script:
    - composer acceptance-test
    
unit-test:
  stage: test
  script: 
    - composer unit-test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

deploy_preprod:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ~/.composer/vendor/bin/envoy run deploy
  environment:
    name: preprod
    url: http://164.132.58.255
  when: on_success
